name: Docker Build

on:
  push:
    branches:
      - '*'
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case repository
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'
      
      - name: Build and push hello_world image
        run: |
          docker build -t ghcr.io/${REPOSITORY_LC}:hello ./hello
          docker push ghcr.io/${REPOSITORY_LC}:hello
        
      - name: Build and push quicksort image
        run: |
          docker build -t ghcr.io/${REPOSITORY_LC}:quicksort ./quicksort
          docker push ghcr.io/${REPOSITORY_LC}:quicksort

          # Tag quicksort as the latest image if the push is to the main branch
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            docker tag ghcr.io/${REPOSITORY_LC}:quicksort ghcr.io/${REPOSITORY_LC}:latest
            docker push ghcr.io/${REPOSITORY_LC}:latest
          fi